name: Merge json files
description: Merge two json files into one. If a key collision occurs, the priority is given to file 2.
author: 'l.boudreau@agendrix.com'
inputs:
  key: 
    required: false
    description: "Name of the field that uniquely identifies an item"
    default: "name"
  file_1_path:
    required: false
    description: Path of the first json file
  file_2_path:
    required: false
    description: Path of the first json file
outputs:
  merged_file_path:
    description: Path to the merged json file 
runs:
  using: 'node16'
  main: 'dist/index.js'
