name: Merge json files
description: Merge json files into one. If a key collision occurs, the priority is given to the file file with the highest index in the array.
author: 'l.boudreau@agendrix.com'
inputs:
  key: 
    required: false
    description: "Name of the field that uniquely identifies an item"
    default: "name"
  files_path:
    required: true
    description: Path of the json files
outputs:
  merged_file_path:
    description: Path to the merged json file 
runs:
  using: 'node16'
  main: 'dist/index.js'
